image:
  - Visual Studio 2019

branches:
  only:
    - neural_network

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,unzip,automake,automake1.16,autoconf,autoconf2.5,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,libtool,wget,liblzma-devel,libcurl-devel,R,libncurses-devel
    CYG_ROOT: C:\cygwin64
    CYG_CACHE: C:\cygwin64\var\cache\setup
    CYG_SETUP: setup-x86_64.exe
    BASH: C:\cygwin64\bin\bash
    CC: gcc
    PYTHON: "C:\\Python37"


# Cache Cygwin/MSYS files to speed up build
cache:
    - '%CYG_CACHE%'
clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - set HOME=.
  - SET PATH=%PYTHON%;%PATH%
  - ps: if (Test-Path Env:\CYG_ROOT) { Start-FileDownload "https://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP" }
  - '%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also'
  - 'python -m ensurepip'
  - 'python -m pip install -r requirements.txt'
  - '%BASH% -lc "cd manual_annotator && bash build_executable.sh'


artifacts:
  - path: mykrobe.command_line.windows.${APPVEYOR_REPO_TAG_NAME}.tar.gz
    type: File

